/**
 * MOCK — a small multiple-choice bank so Margin Call has concept questions before the real topic
 * banks land (D1–D4). Typed as `Question` and id-prefixed by topic, so each one can move into its
 * topic file unchanged; once they exist, the mode draws from those instead and this file goes.
 */
import type { Question } from "@/types/question";

export const MOCK_CONCEPT_QUESTIONS: Question[] = [
  {
    id: "accounting-m01",
    topic: "accounting",
    difficulty: 1,
    prompt: "Depreciation goes up by $10. Before taxes, what happens to net income?",
    choices: ["Up $10", "Down $10", "No change", "Down $6"],
    answerIndex: 1,
    explanation: "Depreciation is an expense, so pre-tax income falls by the full $10.",
  },
  {
    id: "accounting-m02",
    topic: "accounting",
    difficulty: 1,
    prompt: "Which statement shows a company's position at a single point in time?",
    choices: ["Income statement", "Cash flow statement", "Balance sheet", "Statement of equity"],
    answerIndex: 2,
    explanation: "The balance sheet is a snapshot; the other two cover a period.",
  },
  {
    id: "three-statements-m01",
    topic: "three-statements",
    difficulty: 2,
    prompt: "Depreciation rises $10 at a 40% tax rate. Where does cash end up?",
    choices: ["Down $10", "Up $4", "Down $4", "Up $10"],
    answerIndex: 1,
    explanation:
      "Net income falls $6, but the $10 non-cash add-back on the cash flow statement nets to +$4.",
  },
  {
    id: "three-statements-m02",
    topic: "three-statements",
    difficulty: 2,
    prompt: "Accounts receivable increases. On the cash flow statement, that is…",
    choices: ["A source of cash", "A use of cash", "A financing inflow", "Not shown"],
    answerIndex: 1,
    explanation: "Revenue booked but not yet collected — cash hasn't arrived, so it's a use.",
  },
  {
    id: "ratios-m01",
    topic: "ratios",
    difficulty: 1,
    prompt: "Current ratio is…",
    choices: [
      "Current assets ÷ current liabilities",
      "Total debt ÷ equity",
      "EBIT ÷ interest expense",
      "Cash ÷ total assets",
    ],
    answerIndex: 0,
    explanation: "It measures whether short-term assets cover short-term obligations.",
  },
  {
    id: "ratios-m02",
    topic: "ratios",
    difficulty: 2,
    prompt: "Interest coverage of 1.5x most likely signals…",
    choices: [
      "Comfortable leverage",
      "Thin ability to service debt",
      "A cash-rich firm",
      "Low capex",
    ],
    answerIndex: 1,
    explanation: "EBIT covers interest only 1.5 times — a small earnings dip threatens payments.",
  },
  {
    id: "valuation-m01",
    topic: "valuation",
    difficulty: 1,
    prompt: "Enterprise value equals equity value plus…",
    choices: ["Cash, minus debt", "Debt, minus cash", "Revenue", "Retained earnings"],
    answerIndex: 1,
    explanation: "EV adds the claims of lenders (net debt) to those of shareholders.",
  },
  {
    id: "valuation-m02",
    topic: "valuation",
    difficulty: 2,
    prompt: "Which multiple pairs correctly with enterprise value?",
    choices: ["EV / Net income", "EV / EPS", "EV / EBITDA", "EV / Book equity"],
    answerIndex: 2,
    explanation: "EBITDA is pre-interest, so it belongs to all capital holders — like EV.",
  },
  {
    id: "dcf-m01",
    topic: "dcf",
    difficulty: 2,
    prompt: "Raising the discount rate in a DCF does what to the value?",
    choices: ["Increases it", "Decreases it", "No effect", "Only changes the terminal year"],
    answerIndex: 1,
    explanation: "Future cash flows are divided by a bigger number, so present value falls.",
  },
  {
    id: "dcf-m02",
    topic: "dcf",
    difficulty: 3,
    prompt: "Unlevered free cash flow starts from EBIT × (1 − t) and then…",
    choices: [
      "Adds D&A, subtracts capex and the change in NWC",
      "Subtracts interest and adds debt raised",
      "Adds dividends",
      "Subtracts D&A and adds capex",
    ],
    answerIndex: 0,
    explanation: "Add back non-cash D&A, then fund reinvestment: capex and working capital.",
  },
  {
    id: "dcf-m03",
    topic: "dcf",
    difficulty: 3,
    prompt: "Gordon growth terminal value at year 5 uses which cash flow?",
    choices: ["Year 5 FCF", "Year 6 FCF", "Average FCF", "Year 1 FCF"],
    answerIndex: 1,
    explanation: "TV = FCF₆ ÷ (r − g): the first cash flow of the perpetuity, one year out.",
  },
  {
    id: "comps-m01",
    topic: "comps",
    difficulty: 2,
    prompt: "Why exclude a target's one-off restructuring charge from EBITDA in comps?",
    choices: [
      "It's a cash item",
      "It distorts the recurring earnings the multiple prices",
      "Regulators require it",
      "It raises the multiple",
    ],
    answerIndex: 1,
    explanation:
      "Multiples price ongoing earnings power; one-offs make the company look unlike itself.",
  },
  {
    id: "ma-m01",
    topic: "ma",
    difficulty: 2,
    prompt: "An all-stock deal is accretive when the buyer's P/E is…",
    choices: ["Lower than the target's", "Higher than the target's", "Equal to it", "Negative"],
    answerIndex: 1,
    explanation: "Expensive stock buys cheaper earnings, so combined EPS rises.",
  },
  {
    id: "lbo-m01",
    topic: "lbo",
    difficulty: 2,
    prompt: "Which most directly increases an LBO's IRR, all else equal?",
    choices: [
      "More equity at entry",
      "A higher entry multiple",
      "More debt at entry",
      "Slower paydown",
    ],
    answerIndex: 2,
    explanation: "Less equity for the same exit value means a bigger return on that equity.",
  },
  {
    id: "lbo-m02",
    topic: "lbo",
    difficulty: 3,
    prompt: "Doubling your money over 5 years is an IRR of roughly…",
    choices: ["10%", "15%", "20%", "25%"],
    answerIndex: 1,
    explanation: "2x in 5 years is about 14.9% — the 2x/5y ≈ 15% rule of thumb.",
  },
];
